
# Global variables
option = ""
account_select = ""

# NEW / MODIFY - Method to user insert a new personal password and to modify an old one.
def password_personal():
    print("Personal PW")

# NEW - Method to generate a new random password.
def password_random():
    print("Random PW")

# VERIFY - Method to user see the password.
def accounts_show():
    print("Show PW")

# VERIFY - Method to modify the password for a new one, will gona change (delete old - add the new).
def accounts_modify():
    print("Modify PW")

# VERIFY - Method to delete all information from a certain account selected by the user.
def accounts_delete():
    print("Delete data")

# MAIN MENU - Method to close the program - Option [Q]
def quit_program():
    print("Thanks! Closing the program.")

# MAIN MENU - Method to create a new account information and password - Option [N]
def new_password():
    print("""
#################################    
#####   CREAT NEW ACCOUNT   #####
#################################

Before storing your new account, choose whether you prefer 
your personal password or one generated by the program.

[R] - Random password.
[P] - Personal password.
[B] - Back to main menu.
    """)
    option = input("Your selection: ")
    if option == "R":
        password_random()
    elif option == "P":
        password_personal()
    elif option == "B":
        main()
    else:
        print("""
Wrong command! Should be one of the three options! Please, select again.
[R] - Random password.
[P] - Personal password.
[B] - Back to main menu.
        """)
        option = input("Your selection: ")

# MAIN MENU - Method to verify all accounts (see, modify or delete) - Option [V]
def verify_accounts():
    print("""
###############################
#####   VERIFY ACCOUNTS   #####
###############################

Here all the accounts stored in the database.
Select the account you want to access.
    """)
    # GET INFORMATIONS FROM DATA AND SHOW OPTIONS (Nº - NAME)
    account_select = input("Select account: ")
    print("""
Now select the action you want to perform.
[S] - Show account informations.
[M] - Modify account password.
[D] - Delete account informations.
[B] - Back to main menu.
    """)
    option = input("Your selection: ")
    if option == "S":
        accounts_show()
    elif option == "M":
        accounts_modify()
    elif option == "D":
        accounts_delete()
    elif option == "B":
        main()
    else:
        print("""
Wrong command! Should be one of the four options! Please, select again.
[S] - Show account informations.
[M] - Modify account password.
[D] - Delete account informations.
[B] - Back to main menu.
        """)
        option = input("Your selection: ")

def main():
    print("""
#########################
#####   MAIN MENU   #####
#########################

Choose one option:
[N] - New password.
[V] - Verify accounts.
[Q] - Quit the program.
    """)
    option = input("Your selection: ")
    if option == 'N':
        new_password()
    elif option == "V":
        verify_accounts()
    elif option == "Q":
        quit_program()
    else:
        print("""
Wrong command! Should be one of the three options! Please, select again.
[N] - New password.
[V] - Verify accounts.
[Q] - Quit the program.
        """)
        option = input("Your selection: ")

# Main menu welcome text introduction.
print("""
###########################################################
################# WELCOME TO MASTER KEY ###################
###########################################################""")
main()